id: I217C873C
legacy_id: P003092
ocr_import_info:
  bdrc_scan_id: W00EGS1017014
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T03:20:44'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T10:56:14.957007+00:00'
last_modified: 2022-08-29 18:56:30.838375
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1017014
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1017014
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལམ་ཟབ་བླ་མའི་རྣལ་འབྱོར་གྱི་རྣམ་བཤད་བཀའ་བརྒྱུད་རིན་པོ་ཆེའི་དགོངས་རྒྱན།
  author: ལྷོ་ཆེན ༠༣་དཀོན་མཆོག་འཕྲིན་ལས་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.96489266244154
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00EGS1017016:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017016
      total_pages: 100
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1017016.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.96489266244154
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
